---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test-nginx-raw
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
