---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonarqube
helmCharts:
- name: sonarqube
  repo: https://SonarSource.github.io/helm-chart-sonarqube
  version: 2025.4.2
  releaseName: sonarqube
  namespace: sonarqube
  valuesFile: values.yaml

resources:
- namespace.yaml
- ingress.yaml

configMapGenerator:
- name: sonarqube-config
  files:
  - sonar.properties

secretGenerator:
- name: sonarqube-secrets
  literals:
  - postgresql-password=your-secure-password
  - sonarqube-admin-password=admin-secure-password
  - monitoring-passcode=monitoring-secret-code