apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-github-oauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: backstage-github-oauth
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: backstage/github_oauth
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None