---
backstage:
  image:
    registry: ghcr.io
    repository: backstage/backstage
    tag: latest

  appConfig:
    app:
      title: shoutsky lab
      baseUrl: http://backstage.skylarhoughtongithub.local
    
    organization:
      name: shoutsky
    
    backend:
      baseUrl: http://backstage.skylarhoughtongithub.local
      listen:
        port: 7007
        host: 0.0.0.0
      cors:
        origin: http://backstage.skylarhoughtongithub.local
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: better-sqlite3
        connection: ':memory:'

    auth:
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

    techdocs:
      builder: 'local'
      generator:
        runIn: 'docker'
      publisher:
        type: 'local'
    
    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Resource, Location]
      locations:
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

  extraEnvVars:
    - name: NODE_ENV
      value: development
    - name: GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: backstage-github-oauth
          key: client-id
    - name: GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: backstage-github-oauth
          key: client-secret
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: backstage-github-oauth
          key: token

  extraVolumeMounts: []
  extraVolumes: []

postgresql:
  enabled: false
  # Enable if you want to use PostgreSQL instead of SQLite
  # auth:
  #   postgresPassword: "your-password"
  #   database: backstage