---
global:
  imagePullSecrets:
    - ecr-registry-secret

backstage:
  image:
    registry: 635314249418.dkr.ecr.us-east-2.amazonaws.com
    repository: shoutsky-backstage
    tag: latest
    

  appConfig:
    app:
      title: shoutsky lab
      baseUrl: http://backstage.skylarhoughtongithub.local
    
    organization:
      name: shoutsky
    
    backend:
      baseUrl: http://backstage.skylarhoughtongithub.local
      listen:
        port: 7007
        host: 0.0.0.0
      cors:
        origin: http://backstage.skylarhoughtongithub.local
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: pg
        connection:
          host: backstage-postgresql
          port: 5432
          user: backstage
          password: ${POSTGRES_PASSWORD}
          database: backstage

    auth:
      providers:
        guest: {}
        github:
          development:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

    techdocs:
      builder: 'local'
      generator:
        runIn: 'docker'
      publisher:
        type: 'local'
    
    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Resource, Location]
      locations:
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml
        - type: url
          target: https://github.com/SkylarHoughtonGithub/skylab-backstage-catalog/blob/main/eks/template.yaml
          rules:
          - allow: [Template]

  extraEnvVars:
    - name: NODE_ENV
      value: development
    - name: GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: backstage-github-oauth
          key: client-id
    - name: GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: backstage-github-oauth
          key: client-secret
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: backstage-github-oauth
          key: token
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: backstage-postgresql-creds
          key: user-password

  extraVolumeMounts: []
  extraVolumes: []

postgresql:
  enabled: true
  auth:
    username: backstage
    existingSecret: "backstage-postgresql-creds"
    secretKeys:
      adminPasswordKey: admin-password
      userPasswordKey: user-password