---
nginx:
  replicaCount: 1
  
  service:
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: false
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi