---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use remote Redis manifests
resources:
- https://raw.githubusercontent.com/kubernetes/examples/master/staging/storage/redis/redis-deployment.yaml
- https://raw.githubusercontent.com/kubernetes/examples/master/staging/storage/redis/redis-service.yaml

# Add common labels
commonLabels:
  app: test-redis
  managed-by: argocd

# Add namespace
namespace: test-redis-kustomize
