---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tetris-react
resources:
  - namespace.yaml
  - ingress.yaml
  - deployment.yaml
  - service.yaml
commonLabels:
  backstage.io/kubernetes-id: tetris