---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: crossplane-ec2
spec:
  forProvider:
    region: us-east-2
    instanceType: t3.micro
    imageId: ami-0932dc199872f58f8
    keyName: skylab
    subnetId: subnet-0c76bff511c4be88b
    securityGroupIds:
      - sg-0c378988c930cd677
    userData: |
      #!/bin/bash
      yum update -y
      yum install -y httpd
      systemctl start httpd
      systemctl enable httpd
      echo "<h1>Hello from Crossplane EC2!</h1>" > /var/www/html/index.html
    tags:
      - key: Name
        value: crossplane-test-instance
      - key: Environment
        value: dev
      - key: ManagedBy
        value: crossplane
  providerConfigRef:
    name: default