---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: crossplane-ec2
spec:
  forProvider:
    region: us-east-2
    instanceType: t3.micro
    imageId: ami-0932dc199872f58f8
    keyName: skylab
    subnetId: subnet-0c76bff511c4be88b
    securityGroupIds:
      - sg-0c378988c930cd677
    userData: IyEvYmluL2Jhc2gKeXVtIHVwZGF0ZSAteQp5dW0gaW5zdGFsbCAteSBodHRwZApzeXN0ZW1jdGwgc3RhcnQgaHR0cGQKc3lzdGVtY3RsIGVuYWJsZSBodHRwZAplY2hvICI8aDE+SGVsbG8gZnJvbSBDcm9zc3BsYW5lIEVDMiE8L2gxPiIgPiAvdmFyL3d3dy9odG1sL2luZGV4Lmh0bWw=
    tags:
      - key: Name
        value: crossplane-test-instance
      - key: Environment
        value: dev
      - key: ManagedBy
        value: crossplane
  providerConfigRef:
    name: default