---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: crossplane-nodegroup-general
spec:
  forProvider:
    region: us-east-2
    clusterNameRef:
      name: crossplane-eks
    nodeRoleRef:
      name: eks-node-role
    subnetRefs:
      - name: skylab-crossplane-us-east-2a
      - name: skylab-crossplane-us-east-2c
    scalingConfig:
      desiredSize: 1
      maxSize: 1
      minSize: 1
    instanceTypes:
      - t3.medium
    updateConfig:
      force: true
    tags:
      Name: crossplane-nodegroup-general
      Environment: dev
      ManagedBy: crossplane
  providerConfigRef:
    name: default