---
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: crossplane-eks
spec:
  forProvider:
    region: us-east-2
    version: "1.28"
    roleArnRef:
      name: eks-cluster-role
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: false
      securityGroupIdRefs:
        - name: sg-0c378988c930cd677
      subnetIdRefs:
        - name: subnet-0c76bff511c4be88b
        - name: subnet-098f907e237006ac8
    tags:
      Name: crossplane-eks
      Environment: dev
      ManagedBy: crossplane
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: crossplane-eks-conn
    namespace: crossplane-aws-resources