---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: skylab-public-rt
spec:
  forProvider:
    region: us-east-2
    vpcIdRef:
      name: skylab-crossplane-vpc
    associations:
      - subnetIdRef:
          name: skylab-public-us-east-2a
      - subnetIdRef:
          name: skylab-public-us-east-2c
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: skylab-igw
    tags:
      - key: Name
        value: skylab-public-rt
      - key: Environment
        value: dev
      - key: ManagedBy
        value: crossplane
  providerConfigRef:
    name: default
