---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: skylab-public-rt
spec:
  forProvider:
    region: us-east-2
    vpcIdRef:
      name: skylab-crossplane-vpc
    tags:
      - key: Name
        value: skylab-public-rt
      - key: Environment
        value: dev
      - key: ManagedBy
        value: crossplane
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Route
metadata:
  name: skylab-public-route
spec:
  forProvider:
    region: us-east-2
    routeTableIdRef:
      name: skylab-public-rt
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdRef:
      name: skylab-igw
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: skylab-public-rta-2a
spec:
  forProvider:
    region: us-east-2
    routeTableIdRef:
      name: skylab-public-rt
    subnetIdRef:
      name: skylab-public-us-east-2a
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: skylab-public-rta-2c
spec:
  forProvider:
    region: us-east-2
    routeTableIdRef:
      name: skylab-public-rt
    subnetIdRef:
      name: skylab-public-us-east-2c
  providerConfigRef:
    name: default