---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: skylab-crossplane-us-east-2a
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2a
    cidrBlock: 192.168.10.0/24
    vpcIdRef:
      name: skylab-vpc
    tags:
      - key: Name
        value: skylab-crossplane-us-east-2a
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: skylab-crossplane-us-east-2c
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2c
    cidrBlock: 192.168.11.0/24
    vpcIdRef:
      name: skylab-vpc
    tags:
      - key: Name
        value: skylab-crossplane-us-east-2c
  providerConfigRef:
    name: default