---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: skylab-crossplane-vpc
spec:
  deletionPolicy: Orphan
  forProvider:
    region: us-east-2
    cidrBlock: 192.168.0.0/16
    enableDnsHostNames: true
    enableDnsSupport: true
    instanceTenancy: default
    tags:
      - key: Name
        value: skylab-crossplane-vpc
  providerConfigRef:
    name: default