---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: skylab-vpc
  annotations:
    crossplane.io/external-name: vpc-0b03763a7a78b563b
spec:
  deletionPolicy: Orphan
  forProvider:
    region: us-east-2
    cidrBlock: 192.168.0.0/16
    enableDnsHostNames: true
    enableDnsSupport: true
    instanceTenancy: default
    tags:
      - key: Name
        value: skylab-vpc
  providerConfigRef:
    name: default